name: Build 
on: 
    workflow_dispatch:
        inputs: 
            branch:
                description: "inserisci il nome della branch"
jobs:
    build:
      runs-on: windows-latest
      steps:
        - name: checkout repository
          uses: actions/checkout@v3

        - name: Setup node 
          uses: actions/setup-node@v3
          with:
            node-version: 18.x

        - name: install npm 
          run: npm install  
      
        - name: Execute with npm 
          run: npm run build
